### ISSUE TITLE
Support for both way synchronization

### ISSUE THREAD

**Issue by methyl** [redbooth/backbone-redux#3]
Do you have any plans to add synchronizations in both ways?

Right now, if collection is changed, then store is updated properly. The case to update collection when store is changed is not handled at all, and it seems to be very useful as well.

**Comment by somebody32** [comment]
Hi!

Could you please provide a possible use case for this? In other words: why do you want to update the store and then update the collection and not the other way around?

**Comment by methyl** [comment]
The usecase is pretty much straightforward.

Let's assume we have an application in Backbone which we want to move slowly to Redux. When synchronizing just Collections -> Store, we are not able to call any Redux action which will modify/add/remove data, because this action will not be reflected in collection. Generally this means we are stick to push data through Collections if we want to keep them updated in Backbone application.

The solution seems to be fairly simple, just subscribe() to store and set the data on collection.

Does that make sense @somebody32?

**Comment by somebody32** [comment]
I understand the usecase, but I'm really concerned that it may overcomplicate things a lot, just think about these possible edge-cases:
- when changes are passed back to the collection/model, should we call save? If yes, then just imagine possible amount of requests and new events that this will trigger
- what if changes from the store will fail validation on the model? then we will be not in sync
- what if the same record is changed in the store and in the collection? Then you will have race conditions

I think it is **way** easier to think about your data flow if all the changes are propagated only one-way, but with back way synchronization this will be not possible at all

**Comment by methyl** [comment]
So how would you change your data from Redux part of application?

**Comment by somebody32** [comment]
Just treat your BB collections as a single source of truth and let UI reflect the changes, this is the easiest thing to implement and to understand without any big downsides

**Comment by methyl** [comment]
So basically you would keep all your Collections as singletons and access them straight from React components? I don't like this idea as if you finally manage to fully migrate to React components, you end up with old Backbone collections. Thanks for sharing thoughts anyway!

Answering your questions:

> when changes are passed back to the collection/model, should we call save? If yes, then just imagine possible amount of requests and new events that this will trigger

We shouldn't, saving is independent action. If you want to save something from Backbone application, do it on model/collection, for Redux part, add action corresponding to what you want to do.

> what if changes from the store will fail validation on the model? then we will be not in sync

Move validations to Redux and remove them from Backbone models.

> what if the same record is changed in the store and in the collection? Then you will have race conditions

The same can happen if you change the same record from two places in your Backbone application. I don't think this will happen often (never seen such case), and solution could be figured out when it does, as it's quite specific to actual shape of application.

**Comment by somebody32** [comment]
If you mean access == mutate, then yes. But reading the data/state is happening from redux tree only.

Also, if you have plan at some day to remove BB collections at all, then you can hide it under the extra layer: ie react will call `MyApp.some_action_creator_to_trigger()` that for now will mutate the collection, but when you are ready, you can replace this with just redux action dispatching.

So, my idea for this library is to provide a set of small utility functions (like `reducer/action/listeners fabrics, index creators and etc`) that will ease you backbone-redux syncing, but not to try to provide one huge solution for every possible case for migrating/using backbone with redux. Hope this makes sense for you

**Comment by methyl** [comment]
Sure it does, just wanted to figure out what's your approach. Thanks for sharing! (and I think we can close this issue for now)

**Comment by somebody32** [comment]
Thanks for the discussion!

**Comment by masylum** [comment]
My two cents is that Backbone Collections offer you actually a good REST interface anyway. Migrating to React/Redux does not give you that piece so sticking with Backbone for that layer works good for us. Most of the React/Flux implementations I've seen implement adhoc Backbone Collections from scratch. No need to reinvent the wheel.

**Comment by methyl** [comment]
@masylum if you have REST and don't want to implement any optimistic updates kind of thing, then I agree this approach is fine

**Comment by methyl** [comment]
> Backbone Collections offer you actually a good REST interface anyway

Sure, but I don't think it's optimal solution for Flux application to push all the data through Backbone Collections. If you were to start a new application, would you use the same solution? If not, why you are tying yourself to this, assuming you want to migrate fully to Redux at some point of time?

Sorry for asking so many questions, I just want to understand your point of view :smile:
