### ISSUE TITLE
What are you using it for?

### ISSUE THREAD

**Issue by somebody32** [redbooth/backbone-redux#6]
If you're using backbone-redux in your project, please leave a comment about your experience and problems that you've solved. It will be very interesting to know how you're using backbone + redux and to hear your war stories. Especially if you're using it in some custom and not very automatic way.

**Comment by masylum** [comment]
I use it to interact with a REST API without all the redux boilerplate.

**Comment by jimitndiaye** [comment]
I'm using it to integrate jointjs graphs into a redux store.

**Comment by HoiDam** [comment]
Not an issue
Should be closed

**Comment by Morantron** [comment]
> Not an issue
> Should be closed

ok sorry
